language: haskell

before_install:
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && cabal update
  - travis/cabal-apt-install --enable-tests --force

script:
  - cabal install --enable-tests
  - hlint src --cpp-define HLINT || true # don't fail for hlint

notifications:
  irc:
    channels:
      - "irc.freenode.org#ermine"
    skip_join: true
    template:
      - "\x0313ermine\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
